# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: "14.1.0"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - run: |
          echo 'Cloning git repository'
          existing_repo='false'
          mkdir -p '/Users/distiller/project'
          cd '/Users/distiller/project'
          git clone --no-checkout "$CIRCLE_REPOSITORY_URL" .
          echo 'Checking out branch'
          git checkout --force -B "$CIRCLE_BRANCH" "$CIRCLE_SHA1"
      - run: git --no-pager log --no-color -n 1 --format='HEAD is now at %h %s'
      - run: 
          name: Build and run tests
          command: fastlane scan
          environment: 
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: Employee Dictionary
      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run: 
                name: Echo
                command: echo "Hello World"

  # build-and-test-branch:
  #   steps:
  #     - run: 
  #         name: Build and run tests
  #         command: fastlane scan
  #         environment: 
  #           # SCAN_DEVICE: iPhone 8
  #           SCAN_SCHEME: Employee Dictionary
  #     - store_test_results:
  #         path: output/scan
  #     - store_artifacts:
  #         path: output

  # merge-to-master: 
  #   macos:
  #     xcode: "14.1.0"
  #   steps:
  #     - run:
  #         name: Echo
  #         command: echo "Hello World"

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build-and-test
