# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: "14.1.0"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - name: Build and run tests
        command: fastlane scan
        environment: 
          SCAN_DEVICE: iPhone 8
          SCAN_SCHEME: Employee Directory
      - store_test_results:
        path: output/scan
      - store_artifacts:
        path: output
 
workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build-and-test
